// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASj08Eys9WGZwvFwKmDUECrw4zFg1om18',
    appId: '1:5104099623:web:f0d5874b5c645eb2300902',
    messagingSenderId: '5104099623',
    projectId: 'todo-app-83c47',
    authDomain: 'todo-app-83c47.firebaseapp.com',
    storageBucket: 'todo-app-83c47.firebasestorage.app',
    measurementId: 'G-K4SBF62TWS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATndy_ufQ-KDw_ltp8P0v5actwgB6s23g',
    appId: '1:5104099623:ios:3f1daea3d302da70300902',
    messagingSenderId: '5104099623',
    projectId: 'todo-app-83c47',
    storageBucket: 'todo-app-83c47.firebasestorage.app',
    androidClientId: '5104099623-7u1hh0au64loufmoat9n089o6sko7111.apps.googleusercontent.com',
    iosClientId: '5104099623-tjfnvimd0qaf38lnjmltlevoagm5dcl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppNew',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATndy_ufQ-KDw_ltp8P0v5actwgB6s23g',
    appId: '1:5104099623:ios:3f1daea3d302da70300902',
    messagingSenderId: '5104099623',
    projectId: 'todo-app-83c47',
    storageBucket: 'todo-app-83c47.firebasestorage.app',
    androidClientId: '5104099623-7u1hh0au64loufmoat9n089o6sko7111.apps.googleusercontent.com',
    iosClientId: '5104099623-tjfnvimd0qaf38lnjmltlevoagm5dcl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppNew',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCayq1WrKhD8Of0BDbhSvJ1z8W52Dij-i0',
    appId: '1:5104099623:android:ace5a8a5296a8e08300902',
    messagingSenderId: '5104099623',
    projectId: 'todo-app-83c47',
    storageBucket: 'todo-app-83c47.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASj08Eys9WGZwvFwKmDUECrw4zFg1om18',
    appId: '1:5104099623:web:d02ba1251a97c2c4300902',
    messagingSenderId: '5104099623',
    projectId: 'todo-app-83c47',
    authDomain: 'todo-app-83c47.firebaseapp.com',
    storageBucket: 'todo-app-83c47.firebasestorage.app',
    measurementId: 'G-M82DHMQ4CP',
  );

}